DROP DATABASE IF EXISTS MoodLighting;
CREATE DATABASE MoodLighting;
USE MoodLighting;

CREATE TABLE MoodUpdate
(
	moodID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	moodDate VARCHAR(255) NOT NULL,
	moodTime VARCHAR(255) NOT NULL,
	moodValue INT NOT NULL,
	mood VARCHAR(255) NOT NULL
);

